repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  # Git style
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-vcs-permalinks
  - id: forbid-new-submodules
  - id: no-commit-to-branch

  # Common errors
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
    exclude: CHANGELOG.md
  - id: check-yaml
  - id: check-merge-conflict
  - id: check-executables-have-shebangs
